// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsTracker;

#nullable disable

namespace SportsTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620174403_AddDescriptionToDamages")]
    partial class AddDescriptionToDamages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SportsTracker.Borrower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Borrower");
                });

            modelBuilder.Entity("SportsTracker.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValueInDecimal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("currentlyActiveReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("inInventory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("currentlyActiveReservationId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("SportsTracker.EquipmentDamage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("borrowerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("damageAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("equipmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("borrowerId");

                    b.HasIndex("equipmentId");

                    b.ToTable("EquipmentDamage");
                });

            modelBuilder.Entity("SportsTracker.EquipmentReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("borrowerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("equipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("reservationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("returnedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("borrowerId");

                    b.HasIndex("equipmentId");

                    b.HasIndex("reservationId");

                    b.ToTable("EquipmentReservation");
                });

            modelBuilder.Entity("SportsTracker.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("beginDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("endDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("SportsTracker.Equipment", b =>
                {
                    b.HasOne("SportsTracker.Reservation", "CurrentlyActiveReservation")
                        .WithMany()
                        .HasForeignKey("currentlyActiveReservationId");

                    b.Navigation("CurrentlyActiveReservation");
                });

            modelBuilder.Entity("SportsTracker.EquipmentDamage", b =>
                {
                    b.HasOne("SportsTracker.Borrower", "borrower")
                        .WithMany()
                        .HasForeignKey("borrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsTracker.Equipment", "equipment")
                        .WithMany("EquipmentDamages")
                        .HasForeignKey("equipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("borrower");

                    b.Navigation("equipment");
                });

            modelBuilder.Entity("SportsTracker.EquipmentReservation", b =>
                {
                    b.HasOne("SportsTracker.Borrower", "borrower")
                        .WithMany()
                        .HasForeignKey("borrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsTracker.Equipment", "Equipment")
                        .WithMany("EquipmentReservations")
                        .HasForeignKey("equipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsTracker.Reservation", "Reservation")
                        .WithMany("EquipmentReservations")
                        .HasForeignKey("reservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Reservation");

                    b.Navigation("borrower");
                });

            modelBuilder.Entity("SportsTracker.Equipment", b =>
                {
                    b.Navigation("EquipmentDamages");

                    b.Navigation("EquipmentReservations");
                });

            modelBuilder.Entity("SportsTracker.Reservation", b =>
                {
                    b.Navigation("EquipmentReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
